title: "HubLink: the service layer"
description: HubLink : Expand your application with log collecting and other functionalities 
google_analytics: UA-73763104-1
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
